services:
  # 66Do Application
  66do:
    build: .
    ports:
      - "3078:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-YoFinance}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3078}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - yofinance-network

  # PostgreSQL Database (for development)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=66do
      - POSTGRES_USER=66do
      - POSTGRES_PASSWORD=66do_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - yofinance-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - yofinance-network

volumes:
  postgres_data:
  redis_data:

networks:
  yofinance-network:
    driver: bridge
