version: '3.8'

services:
  # YoFinance Application
  YoFinance:
    build: .
    ports:
      - "3078:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-YoFinance}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3078}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - YoFinance-network

  # PostgreSQL Database (for development)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=YoFinance
      - POSTGRES_USER=YoFinance
      - POSTGRES_PASSWORD=YoFinance_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - YoFinance-network

  # Redis (for caching and sessions)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - YoFinance-network

  # Nginx (reverse proxy)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - YoFinance
    restart: unless-stopped
    networks:
      - YoFinance-network

volumes:
  postgres_data:
  redis_data:

networks:
  YoFinance-network:
    driver: bridge
