version: '3.8'

services:
  # X Finance Development Server
  xfinance-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3078:3078"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-X Finance}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3078}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - xfinance-dev-network

  # PostgreSQL Database (for development)
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=xfinance_dev
      - POSTGRES_USER=xfinance
      - POSTGRES_PASSWORD=xfinance_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - xfinance-dev-network

  # Redis (for development)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    restart: unless-stopped
    networks:
      - xfinance-dev-network

  # pgAdmin (database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@xfinance.app
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - xfinance-dev-network

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  xfinance-dev-network:
    driver: bridge
