# Cloudflare Pages Configuration
name = "66do"
compatibility_date = "2025-10-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "66domain-db"
database_id = "a0579a97-ef29-4c0a-b146-618d93d0cb2f"

# Environment variables
[vars]
NEXT_PUBLIC_APP_NAME = "66Do"
NEXT_PUBLIC_APP_URL = "https://66do.pages.dev"

# Pages configuration
pages_build_output_dir = "dist"
