# Cloudflare Pages Configuration with D1 Database
name = "yofinance"
compatibility_date = "2025-10-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "yofinance"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "yofinance-db"
database_id = "85477325-049d-43e2-9b86-6bb1d9de0846"

# KV Storage is optional - not needed for basic functionality
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Environment variables
[vars]
NEXT_PUBLIC_APP_NAME = "YoFinance"
NEXT_PUBLIC_APP_URL = "https://yofinance.com"

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages configuration
[pages]
build_output_dir = "out"

# Functions configuration
[functions]
directory = "functions"
