# Cloudflare Pages Configuration
name = "66do"
compatibility_date = "2025-10-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "66do-db"
database_id = "your-new-database-id"

# Environment variables
[vars]
NEXT_PUBLIC_APP_NAME = "66Do"
NEXT_PUBLIC_APP_URL = "https://66do.pages.dev"

# Pages configuration
pages_build_output_dir = "dist"
