# Cloudflare Pages Configuration
name = "yofinance"
compatibility_date = "2025-10-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "yofinance-db"
database_id = "85477325-049d-43e2-9b86-6bb1d9de0846"

# Environment variables
[vars]
NEXT_PUBLIC_APP_NAME = "YoFinance"
NEXT_PUBLIC_APP_URL = "https://yofinance.pages.dev"

# Pages configuration
pages_build_output_dir = "dist"
